"""build-phaseb-structures.py - (re)generate the Phase B region-palette structure
variants (STRUCTURE-REGION-VARIANTS.md) as our own hand-modelled assets and compile
them to .iob, mirroring build-vanilla-structures.py.

These are bespoke, ADR-004-clean re-creations (no third-party files bundled): the
block layouts are produced deterministically here so the source stays diffable, and
each .iob is a build OUTPUT (regenerable). Loot is attached on the jigsaw-piece via
its vanillaLoot table.

The first hand-authored pass produced toy-sized pieces (outposts 5x8x5, tomb 7x4x7).
This rebuild brings them up to the scale of the structures they stand in for: an
enclosed watchtower (footprint 7x7, ~13 tall, cf. the vanilla pillager watchtower and
the 6x11x6 region watchtowers) and a stepped tomb (11x11 base, cf. 9-11 wide region
temples and the 21-wide vanilla desert pyramid).

Usage:
  python build-phaseb-structures.py
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
IRIS = os.path.dirname(HERE)
SRC_DIR = os.path.join(IRIS, "object-src", "jigsaw", "surface")
OUT_DIR = os.path.join(IRIS, "pack-overlay", "objects", "jigsaw", "surface")


# --------------------------------------------------------------------------
# Outpost watchtower (footprint 7x7, height 13): four log stilts carry a raised
# plank deck; an enclosed log-cornered cabin with a doorway and railed window row;
# an overhanging plank roof with a small peak; a loot chest and hanging lanterns.
# Parameterised by wood so each region gets its own palette.
# --------------------------------------------------------------------------
def build_outpost(wood, region):
    W, H, D = 7, 13, 7
    log = "minecraft:%s_log[axis=y]" % wood
    plank = "minecraft:%s_planks" % wood
    fence = "minecraft:%s_fence" % wood
    b = {}
    deck_corners = [(1, 1), (5, 1), (1, 5), (5, 5)]
    # stilts y=0..6
    for (sx, sz) in deck_corners:
        for y in range(0, 7):
            b[(sx, y, sz)] = log
    # cross-braces at mid height to read as a frame
    for y in (3,):
        for x in range(1, 6):
            b[(x, y, 1)] = plank
            b[(x, y, 5)] = plank
        for z in range(1, 6):
            b[(1, y, z)] = plank
            b[(5, y, z)] = plank
    # deck floor y=7 (x1..5, z1..5)
    for x in range(1, 6):
        for z in range(1, 6):
            b[(x, 7, z)] = plank
    # cabin walls y=8..9 around the deck perimeter; log corner posts; front doorway
    for y in (8, 9):
        for x in range(1, 6):
            for z in range(1, 6):
                if not (x in (1, 5) or z in (1, 5)):
                    continue  # interior is open
                if (x, z) in deck_corners:
                    b[(x, y, z)] = log
                elif x == 3 and z == 1:
                    continue  # doorway
                else:
                    b[(x, y, z)] = plank
    # railed window row y=10: log posts at corners, fences between (open lookout)
    for x in range(1, 6):
        for z in range(1, 6):
            if not (x in (1, 5) or z in (1, 5)):
                continue
            b[(x, 10, z)] = log if (x, z) in deck_corners else fence
    # overhanging plank roof y=11 (full 7x7), small peak y=12 (3x3)
    for x in range(0, 7):
        for z in range(0, 7):
            b[(x, 11, z)] = plank
    for x in range(2, 5):
        for z in range(2, 5):
            b[(x, 12, z)] = plank
    # hanging lanterns under the roof
    for (lx, lz) in [(2, 2), (4, 2), (2, 4), (4, 4)]:
        b[(lx, 10, lz)] = "minecraft:lantern[hanging=true]"
    # loot chest on the deck
    b[(3, 8, 3)] = "minecraft:chest[facing=south,type=single,waterlogged=false]"
    return {"_comment": "%s - %s-region palette variant of the pillager outpost "
                        "(Phase B, STRUCTURE-REGION-VARIANTS.md). An enclosed %s "
                        "watchtower on stilts with a railed lookout, a loot chest "
                        "(chests/pillager_outpost on the jigsaw piece) and hanging "
                        "lanterns. Generated by scripts/build-phaseb-structures.py."
                        % (region, wood.replace("_", " "), wood.replace("_", " ")),
            "size": {"w": W, "h": H, "d": D}, "centered": False, "blocks": b}


# --------------------------------------------------------------------------
# Eroded tomb (11x11 base, height 6): a banded terracotta step-pyramid with a
# hollow inner chamber holding a single buried loot chest. Stands in for the
# desert pyramid in the badlands-flavoured terralost region.
# --------------------------------------------------------------------------
def build_eroded_tomb():
    W, H, D = 11, 6, 11
    b = {}
    bands = [
        (0, 0, "minecraft:terracotta"),         # y0: 11x11
        (1, 1, "minecraft:orange_terracotta"),  # y1: 9x9
        (2, 2, "minecraft:white_terracotta"),   # y2: 7x7
        (3, 3, "minecraft:orange_terracotta"),  # y3: 5x5
        (4, 4, "minecraft:terracotta"),         # y4: 3x3
        (5, 5, "minecraft:orange_terracotta"),  # y5: 1x1 capstone
    ]
    for (y, inset, state) in bands:
        for x in range(inset, W - inset):
            for z in range(inset, D - inset):
                b[(x, y, z)] = state
    # hollow a 3x3 inner chamber at y=1 (under the second band) for the chest
    for x in range(4, 7):
        for z in range(4, 7):
            b[(x, 1, z)] = "minecraft:air"
    b[(5, 1, 5)] = "minecraft:chest[facing=south,type=single,waterlogged=false]"
    return {"_comment": "Eroded Tomb - terralost-region (badlands) palette variant of "
                        "the desert pyramid (Phase B, STRUCTURE-REGION-VARIANTS.md). A "
                        "banded terracotta step-pyramid with a hollow inner chamber and a "
                        "buried loot chest (chests/desert_pyramid on the jigsaw piece). "
                        "Generated by scripts/build-phaseb-structures.py.",
            "size": {"w": W, "h": H, "d": D}, "centered": False, "blocks": b}


BUILDERS = {
    "woodland-stockade": lambda: build_outpost("dark_oak", "Woodland Stockade - forests"),
    "savanna-kraal": lambda: build_outpost("acacia", "Savanna Kraal - hot (savanna)"),
    "taiga-outpost": lambda: build_outpost("spruce", "Taiga Outpost - tundra (taiga)"),
    "eroded-tomb": build_eroded_tomb,
}


def main():
    os.makedirs(SRC_DIR, exist_ok=True)
    os.makedirs(OUT_DIR, exist_ok=True)
    for name, builder in BUILDERS.items():
        spec = builder()
        blocks = spec.pop("blocks")
        ordered = sorted(blocks.items(), key=lambda kv: (kv[0][1], kv[0][2], kv[0][0]))
        spec["blocks"] = [
            {"x": x, "y": y, "z": z, "state": state}
            for (x, y, z), state in ordered
        ]
        src = os.path.join(SRC_DIR, name + ".json")
        out = os.path.join(OUT_DIR, name + ".iob")
        with open(src, "w", encoding="utf-8") as f:
            json.dump(spec, f, indent=2)
            f.write("\n")
        print("wrote %s (%d blocks)" % (src, len(ordered)))
        rc = subprocess.call([sys.executable,
                              os.path.join(HERE, "json_to_iob.py"), src, out])
        if rc != 0:
            raise SystemExit(rc)
        print("compiled %s" % out)


if __name__ == "__main__":
    main()
