"""build-vanilla-structures.py - (re)generate the previously-missing vanilla
overworld structures as our own hand-modelled assets and compile them to .iob.

Closes the gaps recorded in docs/design/VANILLA-STRUCTURE-COVERAGE.md:
  - swamp-hut       (witch hut on stilts)        -> swamp region
  - desert-well     (sandstone well)             -> hot region
  - buried-treasure (single buried loot chest)   -> tropical region
  - shipwreck       (beached dark-oak hull)      -> tropical region

These are bespoke, ADR-004-clean re-creations (no third-party files bundled): the
block layouts are produced deterministically here so the source stays diffable, and
each .iob is a build OUTPUT (regenerable). Loot is attached on the jigsaw-piece via
its vanillaLoot table, mirroring the cave structure set.

Usage:
  python build-vanilla-structures.py
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
IRIS = os.path.dirname(HERE)
SRC_DIR = os.path.join(IRIS, "object-src", "jigsaw", "surface")
OUT_DIR = os.path.join(IRIS, "pack-overlay", "objects", "jigsaw", "surface")


def _ring(b, x0, x1, z0, z1, y, state):
    for x in range(x0, x1 + 1):
        for z in range(z0, z1 + 1):
            if x in (x0, x1) or z in (z0, z1):
                b[(x, y, z)] = state


# --------------------------------------------------------------------------
# desert-well : 5x4x5 cut-sandstone well with a central water pool
# --------------------------------------------------------------------------
def build_desert_well():
    W, H, D = 5, 4, 5
    b = {}
    # floor
    for x in range(W):
        for z in range(D):
            b[(x, 0, z)] = "minecraft:cut_sandstone"
    # walls (perimeter) y=1, inner 3x3 water
    for x in range(W):
        for z in range(D):
            if x in (0, 4) or z in (0, 4):
                b[(x, 1, z)] = "minecraft:cut_sandstone"
            else:
                b[(x, 1, z)] = "minecraft:water[level=0]"
    # corner pillars y=2
    for (cx, cz) in [(0, 0), (4, 0), (0, 4), (4, 4)]:
        b[(cx, 2, cz)] = "minecraft:cut_sandstone"
    # roof ring of slabs y=3 over the corners + edges
    _ring(b, 0, 4, 0, 4, 3, "minecraft:cut_sandstone_slab[type=bottom,waterlogged=false]")
    return {"_comment": "Desert Well - bespoke re-creation of the vanilla desert "
                        "well (cut-sandstone frame, central water pool, slab cap). "
                        "Generated by scripts/build-vanilla-structures.py.",
            "size": {"w": W, "h": H, "d": D}, "centered": False, "blocks": b}


# --------------------------------------------------------------------------
# buried-treasure : 3x3x3, a single loot chest sealed under sand
# --------------------------------------------------------------------------
def build_buried_treasure():
    W, H, D = 3, 3, 3
    b = {}
    for x in range(W):
        for z in range(D):
            b[(x, 0, z)] = "minecraft:sand"
            b[(x, 2, z)] = "minecraft:sand"
    # ring of sand around the chest on the middle layer, chest in the centre
    for x in range(W):
        for z in range(D):
            b[(x, 1, z)] = "minecraft:sand"
    b[(1, 1, 1)] = "minecraft:chest[facing=north,type=single,waterlogged=false]"
    return {"_comment": "Buried Treasure - bespoke re-creation of the vanilla beach "
                        "buried-treasure chest, sealed inside a sand pocket. Loot is "
                        "the chests/buried_treasure table on the jigsaw piece. "
                        "Generated by scripts/build-vanilla-structures.py.",
            "size": {"w": W, "h": H, "d": D}, "centered": False, "blocks": b}


# --------------------------------------------------------------------------
# swamp-hut : 7x7x9 witch hut on oak-log stilts
# --------------------------------------------------------------------------
def build_swamp_hut():
    W, H, D = 7, 7, 9
    b = {}
    # stilts (oak logs) at the four platform corners, y=0..2
    stilts = [(1, 1), (5, 1), (1, 7), (5, 7)]
    for (sx, sz) in stilts:
        for y in range(0, 3):
            b[(sx, y, sz)] = "minecraft:oak_log[axis=y]"
    # platform floor y=3 (spruce planks) spanning x=1..5, z=1..7
    for x in range(1, 6):
        for z in range(1, 8):
            b[(x, 3, z)] = "minecraft:spruce_planks"
    # walls y=4..5 (spruce planks) around the platform, front doorway at x=3
    for y in (4, 5):
        for x in range(1, 6):
            for z in range(1, 8):
                if x in (1, 5) or z in (1, 7):
                    if z == 1 and x == 3 and y in (4, 5):
                        continue  # doorway
                    b[(x, y, z)] = "minecraft:spruce_planks"
    # corner posts up to the eaves (oak logs) y=4..5
    for (cx, cz) in [(1, 1), (5, 1), (1, 7), (5, 7)]:
        for y in (4, 5):
            b[(cx, y, cz)] = "minecraft:oak_log[axis=y]"
    # roof y=6 (spruce planks)
    for x in range(1, 6):
        for z in range(1, 8):
            b[(x, 6, z)] = "minecraft:spruce_planks"
    # interior fittings on the floor-level inside (y=4)
    b[(2, 4, 2)] = "minecraft:cauldron[level=3]"
    b[(4, 4, 2)] = "minecraft:crafting_table"
    b[(2, 4, 6)] = "minecraft:red_mushroom"
    b[(4, 4, 6)] = "minecraft:oak_fence[north=false,south=false,east=false,west=false,waterlogged=false]"
    b[(4, 5, 6)] = "minecraft:flower_pot"
    return {"_comment": "Swamp Hut - bespoke re-creation of the vanilla witch hut: "
                        "oak-log stilts, raised spruce-plank cabin with a cauldron, "
                        "crafting table, mushroom and a potted plant. No vanilla loot "
                        "chest (matches vanilla). Generated by "
                        "scripts/build-vanilla-structures.py.",
            "size": {"w": W, "h": H, "d": D}, "centered": False, "blocks": b}


# --------------------------------------------------------------------------
# shipwreck : 5x6x13 beached dark-oak hull with mast and loot chests
# --------------------------------------------------------------------------
def build_shipwreck():
    W, H, D = 5, 6, 13
    b = {}

    def hull_half_width(z):
        # taper the hull towards bow (z=0) and stern (z=D-1)
        if z <= 1 or z >= D - 2:
            return 1
        if z <= 3 or z >= D - 4:
            return 2
        return 2

    # keel + hull bottom (y=0..1)
    for z in range(D):
        hw = hull_half_width(z)
        for x in range(2 - hw, 2 + hw + 1):
            b[(x, 0, z)] = "minecraft:dark_oak_log[axis=z]" if x == 2 else "minecraft:dark_oak_planks"
            b[(x, 1, z)] = "minecraft:dark_oak_planks"
    # hull sides (y=2..3): only the outer edge of each row
    for y in (2, 3):
        for z in range(1, D - 1):
            hw = hull_half_width(z)
            for x in (2 - hw, 2 + hw):
                if 0 <= x < W:
                    b[(x, y, z)] = "minecraft:dark_oak_planks"
        # bow / stern caps
        b[(2, y, 0)] = "minecraft:dark_oak_planks"
        b[(2, y, D - 1)] = "minecraft:dark_oak_planks"
    # partial deck (y=2) across the mid-section
    for z in range(4, D - 4):
        for x in range(1, 4):
            b[(x, 2, z)] = "minecraft:dark_oak_planks"
    # mast (oak log) rising from mid-deck
    mast_z = D // 2
    for y in range(3, 6):
        b[(2, y, mast_z)] = "minecraft:oak_log[axis=y]"
    # a small sail spar
    b[(1, 5, mast_z)] = "minecraft:white_wool"
    b[(3, 5, mast_z)] = "minecraft:white_wool"
    # loot chests: supply (mid), treasure (stern), map (bow)
    b[(2, 2, 5)] = "minecraft:chest[facing=north,type=single,waterlogged=false]"
    b[(2, 1, D - 2)] = "minecraft:chest[facing=south,type=single,waterlogged=false]"
    b[(2, 1, 1)] = "minecraft:chest[facing=north,type=single,waterlogged=false]"
    return {"_comment": "Shipwreck - bespoke re-creation of the vanilla shipwreck: a "
                        "beached dark-oak hull with a tapered keel, a short mast with a "
                        "small sail, and three loot chests. Loot tables are attached on "
                        "the jigsaw piece. Generated by "
                        "scripts/build-vanilla-structures.py.",
            "size": {"w": W, "h": H, "d": D}, "centered": False, "blocks": b}


BUILDERS = {
    "desert-well": build_desert_well,
    "buried-treasure": build_buried_treasure,
    "swamp-hut": build_swamp_hut,
    "shipwreck": build_shipwreck,
}


def main():
    os.makedirs(SRC_DIR, exist_ok=True)
    os.makedirs(OUT_DIR, exist_ok=True)
    for name, builder in BUILDERS.items():
        spec = builder()
        blocks = spec.pop("blocks")
        ordered = sorted(blocks.items(), key=lambda kv: (kv[0][1], kv[0][2], kv[0][0]))
        spec["blocks"] = [
            {"x": x, "y": y, "z": z, "state": state}
            for (x, y, z), state in ordered
        ]
        src = os.path.join(SRC_DIR, name + ".json")
        out = os.path.join(OUT_DIR, name + ".iob")
        with open(src, "w", encoding="utf-8") as f:
            json.dump(spec, f, indent=2)
            f.write("\n")
        print(f"wrote {src} ({len(ordered)} blocks)")
        rc = subprocess.call([sys.executable,
                              os.path.join(HERE, "json_to_iob.py"), src, out])
        if rc != 0:
            raise SystemExit(rc)
        print(f"compiled {out}")


if __name__ == "__main__":
    main()
