#!/usr/bin/env python3
"""Strip dead / unsupported keys from overlay biomes for Iris 4.0.

Iris 4.0's ``IrisBiome`` class (verified by decompiling ``Iris.jar``,
``4.0.0-26.1``) does NOT define ``jigsawStructures``, ``biomeZoom`` or
``carving`` as biome fields, and Iris has no comment support, so any
``_comment*`` key is rejected too. At load time Iris logs each of these as an
``Unknown Biome field "..." (Gson will silently ignore this)`` warning.

These keys carry no behaviour in 4.0:

* ``jigsawStructures`` - jigsaw placement moved to the top-level ``structures/``
  system in 4.0; the per-biome array is dead.
* ``carving`` - caves are now a carving model keyed off ``carvingBiome`` /
  ``biomes/carving/``; the inline ``carving`` object is dead.
* ``biomeZoom`` - not a biome field (zoom lives inside ``biomeStyle``).
* ``_comment`` / ``_comment_wall`` / ``_comment_layers`` / ... - author notes
  Iris never understood.

This removes those keys at any nesting depth from raw text so formatting / diffs
stay minimal, fixes the resulting separator commas, validates the JSON, and is
idempotent. Only ``pack-overlay/biomes`` is touched (``pack-base`` is upstream
and git-ignored; the test-server deploy is regenerated by the deploy script).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

OVERLAY_BIOMES = Path(__file__).resolve().parents[1] / "pack-overlay" / "biomes"

EXACT_KEYS = {"jigsawStructures", "biomeZoom", "carving"}


def is_target(key: str) -> bool:
    return key in EXACT_KEYS or key.startswith("_comment")


def _find_string_end(s: str, i: int) -> int:
    """``s[i]`` is the opening quote; return index just past the closing quote."""
    i += 1
    n = len(s)
    while i < n:
        c = s[i]
        if c == "\\":
            i += 2
            continue
        if c == '"':
            return i + 1
        i += 1
    return i


def _skip_ws(s: str, i: int) -> int:
    n = len(s)
    while i < n and s[i] in " \t\r\n":
        i += 1
    return i


def _parse_value(s: str, i: int, deletions: list[tuple[int, int]]) -> int:
    """Return index just past the value starting at ``s[i]`` (non-ws)."""
    c = s[i]
    if c == '"':
        return _find_string_end(s, i)
    if c == "{":
        return _parse_object(s, i, deletions)
    if c == "[":
        return _parse_array(s, i, deletions)
    n = len(s)
    while i < n and s[i] not in ",}]" and s[i] not in " \t\r\n":
        i += 1
    return i


def _parse_array(s: str, i: int, deletions: list[tuple[int, int]]) -> int:
    i += 1  # past '['
    while True:
        i = _skip_ws(s, i)
        if s[i] == "]":
            return i + 1
        i = _parse_value(s, i, deletions)
        i = _skip_ws(s, i)
        if s[i] == ",":
            i += 1
        elif s[i] == "]":
            return i + 1


def _line_start(s: str, i: int) -> int:
    """Start of the line containing ``i`` if only whitespace precedes ``i``."""
    j = i
    while j > 0 and s[j - 1] in " \t":
        j -= 1
    if j == 0 or s[j - 1] == "\n":
        return j
    return i


def _parse_object(s: str, i: int, deletions: list[tuple[int, int]]) -> int:
    i += 1  # past '{'
    pre_comma: int | None = None  # position of the comma before this member
    while True:
        i = _skip_ws(s, i)
        if s[i] == "}":
            return i + 1
        key_start = i
        key_end = _find_string_end(s, i)
        key = s[key_start + 1 : key_end - 1]
        j = _skip_ws(s, key_end)
        # s[j] == ':'
        val_start = _skip_ws(s, j + 1)
        val_end = _parse_value(s, val_start, deletions)
        k = _skip_ws(s, val_end)
        trailing_comma = s[k] == ","

        if is_target(key):
            if trailing_comma:
                # remove the member plus its trailing comma and indentation
                end = k + 1
                while end < len(s) and s[end] in " \t":
                    end += 1
                if end < len(s) and s[end] == "\n":
                    end += 1
                deletions.append((_line_start(s, key_start), end))
            elif pre_comma is not None:
                # last member: drop the preceding comma through this value
                deletions.append((pre_comma, val_end))
            else:
                # only member in the object
                deletions.append((_line_start(s, key_start), val_end))

        if trailing_comma:
            pre_comma = None if is_target(key) else k
            i = k + 1
        else:
            return k + 1  # s[k] == '}'


def strip_unknown(text: str) -> tuple[str, bool]:
    try:
        json.loads(text)
    except json.JSONDecodeError:
        return text, False

    deletions: list[tuple[int, int]] = []
    start = _skip_ws(text, 0)
    _parse_value(text, start, deletions)
    if not deletions:
        return text, False

    deletions.sort()
    out = []
    prev = 0
    for a, b in deletions:
        if a < prev:  # overlap guard
            a = prev
        if a < b:
            out.append(text[prev:a])
            prev = b
    out.append(text[prev:])
    new_text = "".join(out)

    # Tidy any separator comma left dangling before a closing bracket.
    new_text = re.sub(r",(\s*[}\]])", r"\1", new_text)

    try:
        json.loads(new_text)
    except json.JSONDecodeError:
        return text, False
    return new_text, True


def main() -> int:
    if not OVERLAY_BIOMES.is_dir():
        print(f"ERROR: biomes dir not found: {OVERLAY_BIOMES}", file=sys.stderr)
        return 1

    changed = 0
    for path in sorted(OVERLAY_BIOMES.rglob("*.json")):
        original = path.read_text(encoding="utf-8")
        updated, did = strip_unknown(original)
        if did and updated != original:
            path.write_text(updated, encoding="utf-8", newline="\n")
            changed += 1
            print(f"  {path.relative_to(OVERLAY_BIOMES)}: unknown biome field(s) removed")

    print(f"Done. Cleaned {changed} file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
